# This is a sample .blackfire.yaml file created by Blackfire.
# You can read more about .blackfire.yaml here: https://blackfire.io/docs/cookbooks/tests
metrics:
    app.user_activity_calculation:
        label: "User activity calculation"
        timeline: true
        marker: true
        matching_calls:
            python:
                - callee: '=bigfoot.models.User.get_recent_comments_count'

    app.comment_count_annotation:
        label: "Comment count annotation"
        timeline: true
        marker: true
        matching_calls:
            python:
                - callee: '=django.db.models.expressions.Count.resolve_expression'

tests:
    "The homepage should be fast":
        path: "/"
        assertions:
            - "main.wall_time < 100ms"
    
    "The homepage should not consume too much memory":
        path: "/"
        assertions:
            - "main.peak_memory < 2mb"

    "The number of created entities should be reasonable":
        path: "/.*"
        assertions:
            - "metrics.entities.created.count < 50"

    "The homepage should have a limited number of SQL queries":
        path: "/"
        assertions:
            - "metrics.sql.queries.count <= 5"

    "User activity calculation should be cached":
        path: "/sighting/.*"
        assertions:
            - "metrics.app.user_activity_calculation.count == 0"

    "Comment count should be annotated to Sighting entity":
        path: "/"
        assertions:
            - "metrics.app.comment_count_annotation.count > 0"

# For writing scenarios, take a look at the documentation
# https://blackfire.io/docs/cookbooks/scenarios
scenarios: |
    #!blackfire-player

    scenario
        name "Basic Visit"
        visit url("/")
            name "Homepage"
            expect status_code() == 200
            expect css("tbody.js-sightings-list tr").count() > 10

        click css('.js-sightings-list > tr:nth-child(3) a')
            name "First sighting page"
            expect status_code() == 200
